---
title: "Abstract selection summary"
format:
  html:
    embed-resources: true
execute:
  echo: false
  warning: false
---

## Summary

The following is a RAP(-ish) process to count how many long talks, short talks, and posters I've accepted as I go along editing the spreadsheet

```{r}

read_sheet <- function(sheet_name){
  
  readxl::read_excel("data/final_abstract_selection.xlsx", sheet = sheet_name)
}

long_talks <- read_sheet("Longer talk")

short_talks <- read_sheet("Short talk")

posters <- read_sheet("Poster")

dfs <- list("Longer talk" = long_talks, "Short talk" = short_talks, "Poster" = posters)

```

## Summary

```{r}

count_accept <- function(df_list, type){
  
  accept <- df_list[[type]] |> 
    dplyr::count(Decision) |> 
    dplyr::filter(Decision == "ACCEPT") |> 
    dplyr::pull(n)
  
  changed <- sum(purrr::map_int(df_list, ~ sum(.x[["Decision"]] == type)))
  
  return(accept + changed)
  
}

long_talk_count <- count_accept(dfs, 'Longer talk')
short_talk_count <- count_accept(dfs, 'Short talk')

print(glue::glue("There are {long_talk_count} long talks, ", 
                 "{short_talk_count} short talks, and {count_accept(dfs, 'Poster')} posters. 
               In total there are {long_talk_count + short_talk_count} talks"))

```

## Longer talks

```{r}

long_talks |> 
  dplyr::count(Decision) |> 
  gt::gt()

```

## Shorter talks

```{r}

short_talks |> 
  dplyr::count(Decision) |> 
  gt::gt()

```

## Posters

```{r}

posters |> 
  dplyr::count(Decision) |> 
  gt::gt()

```






### Note on licence

Crown Copyright, 2023, [MIT licence](https://opensource.org/license/mit/)

